import { motion } from "framer-motion";
import { ArrowRight, Check, Clock3, MapPin, Navigation, ParkingSquare, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "wouter";
import { PublicNav } from "@/components/app-shell";
import { Button, Card, Field, Input, Select } from "@/components/ui";
import { useAuth } from "@/lib/auth";
import type { Role } from "@/lib/api";

export function LandingPage() {
  return <div className="min-h-screen overflow-hidden bg-[#f7f8fa] text-slate-950">
    <PublicNav />
    <section className="relative mx-auto grid min-h-[720px] max-w-7xl items-center gap-16 px-6 pb-20 pt-32 lg:grid-cols-[1.08fr_.92fr] lg:px-10 lg:pt-24">
      <div className="relative z-10">
        <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }} className="mb-6 inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white/70 px-3 py-1.5 text-xs font-semibold text-slate-500 shadow-sm"><Sparkles size={13} className="text-amber-500" /> Parking without the parking lot hunt</motion.div>
        <motion.h1 initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .08, duration: .7 }} className="max-w-2xl text-6xl font-semibold leading-[.96] tracking-[-0.075em] text-slate-950 sm:text-7xl">Arrive with more <span className="text-slate-400">certainty.</span></motion.h1>
        <p className="mt-7 max-w-xl text-lg leading-8 text-slate-500">ORT helps you find a space that fits, reserve it in seconds, and get on with your day. No circling. No guesswork.</p>
        <div className="mt-9 flex flex-wrap gap-3"><Link href="/search" className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3.5 text-sm font-semibold text-white shadow-xl shadow-slate-950/15 hover:bg-slate-800" data-testid="link-hero-search">Find a space <ArrowRight size={16} /></Link><Link href="/signup" className="rounded-xl px-5 py-3.5 text-sm font-semibold text-slate-700 hover:bg-white" data-testid="link-hero-signup">Create an account</Link></div>
        <div className="mt-12 flex flex-wrap gap-7 text-sm text-slate-500"><span className="flex items-center gap-2"><Check size={16} className="text-emerald-600" /> Real-time availability</span><span className="flex items-center gap-2"><Check size={16} className="text-emerald-600" /> Secure reservations</span><span className="flex items-center gap-2"><Check size={16} className="text-emerald-600" /> Built for your city</span></div>
      </div>
      <motion.div initial={{ opacity: 0, scale: .94, rotate: 1 }} animate={{ opacity: 1, scale: 1, rotate: 0 }} transition={{ delay: .18, duration: .8 }} className="relative">
        <div className="absolute -inset-10 rounded-full bg-blue-200/30 blur-3xl" /><Card className="relative overflow-hidden border-0 bg-slate-950 p-3 shadow-2xl shadow-slate-900/20"><div className="relative h-[460px] overflow-hidden rounded-xl bg-[#dfe7e5]"><div className="absolute inset-0 opacity-60" style={{ backgroundImage: "linear-gradient(30deg, transparent 47%, rgba(255,255,255,.55) 48%, rgba(255,255,255,.55) 52%, transparent 53%), linear-gradient(120deg, transparent 47%, rgba(255,255,255,.55) 48%, rgba(255,255,255,.55) 52%, transparent 53%)", backgroundSize: "110px 110px" }} /><div className="absolute inset-x-10 top-20 h-20 rotate-12 rounded-full bg-white/70 blur-sm" /><div className="absolute left-[38%] top-[36%] grid h-16 w-16 place-items-center rounded-full border-8 border-white bg-slate-950 text-white shadow-xl"><Navigation size={20} fill="currentColor" /></div>{[["22%", "25%", "2 min"], ["65%", "22%", "4 min"], ["74%", "67%", "6 min"], ["27%", "72%", "8 min"]].map(([left, top, time], index) => <div key={time} className="absolute" style={{ left, top }}><div className="grid h-11 w-11 place-items-center rounded-full border-4 border-white bg-white text-slate-950 shadow-lg"><ParkingSquare size={16} /></div><span className="absolute left-1/2 top-12 -translate-x-1/2 whitespace-nowrap rounded-full bg-slate-950 px-2 py-1 text-[10px] font-bold text-white">{time}</span></div>)}<div className="absolute bottom-5 left-5 right-5 rounded-2xl border border-white/60 bg-white/90 p-4 shadow-xl backdrop-blur"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-slate-400">Near you</p><p className="mt-1 text-sm font-semibold text-slate-950">42 spaces available</p></div><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-100 text-emerald-700"><MapPin size={17} /></span></div></div></div></Card>
      </motion.div>
    </section>
    <section className="border-t border-slate-200 bg-white px-6 py-20 lg:px-10"><div className="mx-auto max-w-7xl"><div className="grid gap-10 md:grid-cols-3"><div><p className="text-3xl font-semibold tracking-[-.05em]">One calm place<br />to park.</p></div><div className="rounded-2xl bg-slate-50 p-6"><Clock3 className="text-slate-500" size={21} /><p className="mt-8 font-semibold">Know before you go</p><p className="mt-2 text-sm leading-6 text-slate-500">See availability, pricing, and walking distance before you commit.</p></div><div className="rounded-2xl bg-slate-950 p-6 text-white"><ShieldCheck className="text-emerald-400" size={21} /><p className="mt-8 font-semibold">Your plans stay yours</p><p className="mt-2 text-sm leading-6 text-slate-400">Every reservation is attached to your account and easy to manage.</p></div></div></div></section>
  </div>;
}

export function LoginPage() {
  const { login, error } = useAuth();
  const [, setLocation] = useLocation();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [pending, setPending] = useState(false); const [formError, setFormError] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setPending(true); setFormError(""); try { const user = await login(email, password); setLocation(user.role === "owner" ? "/owner" : user.role === "admin" ? "/admin" : "/dashboard"); } catch (cause) { setFormError(cause instanceof Error ? cause.message : "Unable to sign in"); } finally { setPending(false); } }
  return <AuthLayout eyebrow="Welcome back" title="Your next stop starts here." subtitle="Sign in to find a space, manage a reservation, or keep your parking business moving."><form onSubmit={submit} className="grid gap-5"><Field label="Email"><Input data-testid="input-login-email" autoComplete="email" type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" required /></Field><Field label="Password"><Input data-testid="input-login-password" autoComplete="current-password" type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="At least 8 characters" required /></Field>{(formError || error) && <p className="rounded-xl bg-rose-50 px-3 py-2.5 text-sm text-rose-700" data-testid="status-login-error">{formError || error}</p>}<Button data-testid="button-login" type="submit" disabled={pending}>{pending ? "Signing in…" : "Sign in"} <ArrowRight size={16} /></Button><p className="text-center text-sm text-slate-500">New to ORT? <Link href="/signup" className="font-semibold text-slate-950 underline underline-offset-4" data-testid="link-login-signup">Create an account</Link></p></form></AuthLayout>;
}

export function SignupPage() {
  const { register } = useAuth(); const [, setLocation] = useLocation();
  const [role, setRole] = useState<Role>("customer"); const [fullName, setFullName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setPending(true); setError(""); try { const user = await register({ full_name: fullName, email, password, role }); setLocation(user.role === "owner" ? "/owner" : "/dashboard"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to create account"); } finally { setPending(false); } }
  return <AuthLayout eyebrow="Start parking smarter" title="Make room for what matters." subtitle="Create a ORT account in under a minute. Choose a customer account to reserve spaces or an owner account to list yours."><form onSubmit={submit} className="grid gap-5"><Field label="I’m joining as"><Select data-testid="select-signup-role" value={role} onChange={e => setRole(e.target.value as Role)}><option value="customer">A driver looking for parking</option><option value="owner">A parking space owner</option></Select></Field><Field label="Full name"><Input data-testid="input-signup-name" autoComplete="name" value={fullName} onChange={e => setFullName(e.target.value)} placeholder="Alex Morgan" required minLength={2} /></Field><Field label="Email"><Input data-testid="input-signup-email" autoComplete="email" type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" required /></Field><Field label="Password"><Input data-testid="input-signup-password" autoComplete="new-password" type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="At least 8 characters" required minLength={8} /></Field>{error && <p className="rounded-xl bg-rose-50 px-3 py-2.5 text-sm text-rose-700" data-testid="status-signup-error">{error}</p>}<Button data-testid="button-signup" type="submit" disabled={pending}>{pending ? "Creating account…" : "Create account"} <ArrowRight size={16} /></Button><p className="text-center text-sm text-slate-500">Already have an account? <Link href="/login" className="font-semibold text-slate-950 underline underline-offset-4" data-testid="link-signup-login">Sign in</Link></p></form></AuthLayout>;
}

function AuthLayout({ eyebrow, title, subtitle, children }: { eyebrow: string; title: string; subtitle: string; children: React.ReactNode }) {
  return <div className="grid min-h-screen bg-[#f7f8fa] lg:grid-cols-[.9fr_1.1fr]"><div className="relative hidden overflow-hidden bg-slate-950 p-12 text-white lg:flex lg:flex-col lg:justify-between"><Link href="/" className="flex items-center gap-3 text-lg font-semibold" data-testid="link-auth-logo"><span className="grid h-9 w-9 place-items-center rounded-xl bg-white text-slate-950"><ParkingSquare size={19} /></span>ORT</Link><div className="relative z-10 max-w-md pb-12"><p className="text-sm text-slate-400">“The difference between a good day and a stressful one can be a parking spot.”</p><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-slate-500">ORT, made for the arrival</p></div><div className="absolute -right-24 top-1/4 h-96 w-96 rounded-full bg-blue-500/30 blur-3xl" /><div className="absolute -bottom-32 -left-32 h-96 w-96 rounded-full bg-emerald-400/20 blur-3xl" /></div><div className="flex items-center justify-center px-6 py-16"><div className="w-full max-w-md"><Link href="/" className="mb-12 flex items-center gap-3 text-lg font-semibold lg:hidden" data-testid="link-mobile-auth-logo"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-950 text-white"><ParkingSquare size={19} /></span>ORT</Link><div className="mb-8"><p className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-slate-400">{eyebrow}</p><h1 className="text-4xl font-semibold tracking-[-.06em] text-slate-950">{title}</h1><p className="mt-3 text-sm leading-6 text-slate-500">{subtitle}</p></div><Card className="p-6 sm:p-8">{children}</Card></div></div></div>;
}